//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class JogoDaVelha
    {
        public int id { get; set; }
        public Nullable<int> IDJogo { get; set; }
        public int Casa1 { get; set; }
        public int Casa2 { get; set; }
        public int Casa3 { get; set; }
        public int Casa4 { get; set; }
        public int Casa5 { get; set; }
        public int Casa6 { get; set; }
        public int Casa7 { get; set; }
        public int Casa8 { get; set; }
        public int Casa9 { get; set; }
    
        public virtual Jogo Jogo { get; set; }
    }
}
