//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class JogoDaVelha
    {
        public int id { get; set; }
        public Nullable<int> IDJogo { get; set; }
        public int casa1 { get; set; }
        public int casa2 { get; set; }
        public int casa3 { get; set; }
        public int casa4 { get; set; }
        public int casa5 { get; set; }
        public int casa6 { get; set; }
        public int casa7 { get; set; }
        public int casa8 { get; set; }
        public int casa9 { get; set; }
    
        public virtual JOGO JOGO { get; set; }
    }
}
